### ISSUE TITLE
There's no PWA icon

### ISSUE THREAD

**Issue by mielp** [flusio/flusio#166]
Hey 👋 Thanks for making Flus!

I think I read in your blogposts that the Flus webapp should work as a PWA.

However, when I tried to add app.flus.fr on my smartphone's homescreen (an iPhone SE from 2015), iOS displayed a screenshot of the web app instead of a nice icon.

It seems there is no [web app manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest) yet on `app.flus.fr`, which means there will be no app icon and no experience enhancements like automatically hiding the browser UI.

It is very low priority at the moment, but adding a `.webmanifest` and linking to it would likely improve the user experience for folks who want to use Flus as an app 🙂

**Edit:** I learned that currently, the web manifest is only used on Android, and isn't used at all on iOS, which instead relies on two head tags:

```html
<!-- Example PWA tags for iOS -->
<meta name="apple-mobile-web-app-capable" content="yes">
<link rel="apple-touch-icon" sizes="180x180" href="static/icons/icon-180.png">
```

**Comment by marienfressinaud** [comment]
Hey @mielp, I think I never mentioned Flus works as a PWA since it never has been my intention :p I most probably said it's working fine on mobile (implying in a browser). I agree though that having a simple webmanifest would enhance the experience a lot, I'm adding your suggestion to my list. I'll let you know when it'll be done :) Thanks for your suggestion!

**Comment by mielp** [comment]
Oh, my mistake then, I mixed up the concepts 😅

I don't know PHP at all, but if it's just about writing a decent manifest file in the `static` directory and referencing it in the five-ish PHTML layouts the same way the `favicon-32px.png` file is referenced, then I can make the change if you want?

**Comment by marienfressinaud** [comment]
I don't think it should be in the `static/` directory (because of the `name` and `start_url` which can be changed), so it might be a bit more complicated than what you expect.

Also, for the moment, I don't want to encourage PR from other people because it will ask me time/energy to review and integrate. I already have enough to do :sweat_smile:

**Comment by mielp** [comment]
No problem, good luck with all your work! ✨

**Comment by marienfressinaud** [comment]
Hey @mielp, the webmanifest has been added in https://github.com/flusio/flusio/pull/175 and it is now deployed, let me know how it works for you! :)
